changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot[bot]
  categories:
    - title: MCP changes
      labels:
        - mcp
        - mcp-client
    - title: Security
      labels:
        - security
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - dependencies
        - ci
    - title: Other changes
      labels:
        - "*"

