name: Dependency Review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  dependency-review:
    if: github.repository_visibility == 'public'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Review dependency changes
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48
        with:
          fail-on-severity: high

